// Code generated by candi v1.13.11.

package repository

import (
	"context"

	"monorepo/services/warehoouse/internal/modules/brand/domain"
	shareddomain "monorepo/services/warehoouse/pkg/shared/domain"
)

// BrandRepository abstract interface
type BrandRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterBrand) ([]shareddomain.Brand, error)
	Count(ctx context.Context, filter *domain.FilterBrand) int
	Find(ctx context.Context, filter *domain.FilterBrand) (shareddomain.Brand, error)
	Save(ctx context.Context, data *shareddomain.Brand) error
	Delete(ctx context.Context, data *shareddomain.Brand) (err error)
}
