version: '3.4'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: belajar
    volumes:
       - pg-data:/var/lib/postgresql/data

  redis:
    image: 'redis:7-alpine'
    command: redis-server --requirepass passW0RD
    ports:
      - '6389:6379'
    restart: on-failure

volumes:
  pg-data: