// Code generated by candi v1.13.11.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	brandusecase "monorepo/services/warehoouse/internal/modules/brand/usecase"
	"monorepo/services/warehoouse/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Brand() brandusecase.BrandUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		brandusecase.BrandUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.BrandUsecase, setSharedUsecaseFunc = brandusecase.NewBrandUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Brand() brandusecase.BrandUsecase {
	return uc.BrandUsecase
}

