// Code generated by candi v1.13.11. DO NOT EDIT.

package sdk

import (
	"sync"

	// @candi:serviceImport
	"monorepo/sdk/warehoouse"
)

// Option func type
type Option func(*sdkInstance)

var (
	sdk  SDK
	once sync.Once
)

// SetGlobalSDK constructor with each sdk service option.
func SetGlobalSDK(opts ...Option) {
	s := new(sdkInstance)
	for _, o := range opts {
		o(s)
	}
	once.Do(func() {
		sdk = s
	})
}

// GetSDK get global sdk instance
func GetSDK() SDK {
	return sdk
}

// @candi:construct

// SetWarehoouse option func
func SetWarehoouse(warehoouse warehoouse.Warehoouse) Option {
	return func(s *sdkInstance) {
		s.warehoouse = warehoouse
	}
}

// SDK instance abstraction
type SDK interface {
	// @candi:serviceMethod
	Warehoouse() warehoouse.Warehoouse
}

// sdkInstance implementation
type sdkInstance struct {
	// @candi:serviceField
	warehoouse	warehoouse.Warehoouse
}

// @candi:instanceMethod
func (s *sdkInstance) Warehoouse() warehoouse.Warehoouse {
	return s.warehoouse
}
